### ISSUE TITLE
Adding this to terraform builtin

### ISSUE THREAD

**Issue by adamdecaf** [donaldguy/terraform-provider-twilio#1]
Hey! Have you all thought about adding this to terraform as a builtin provider? They're accepting of incoming contributions and it would make it easier for folks to use.

**Comment by donaldguy** [comment]
I have. I don't really have time at the moment to write the tests needed to be up to hashicorp's standards, but if someone wanted to PR those, I'm all for going upstream

**Comment by mleonhard** [comment]
@twilio, This would be helpful to me.  Please consider doing this.

**Comment by donaldguy** [comment]
I no longer work at Tulip and don't have any expectation of revisiting this in the forseeable future; if indeed someone from @twilio wants to grab this code (or write something anew) seems dope

On the Tulip side, @benweissmann might look at it? I'd be honestly a little surprised if Tulip was paying any attention to this repo anymore too tho

**Comment by adamdecaf** [comment]
Terraform providers are in their own Github org now: https://github.com/terraform-providers/

Hashicorp has some automation around them, so we'd need to rework this project to follow those standards.

**Comment by benweissmann** [comment]
At Tulip, we're not actively working on this provider (but I'd be happy to review PRs for urgent bug fixes or security issues). I'm happy to transfer this repo to the terraform-providers org, or link to a replacement, if there's a new maintainer who'd like to work on getting this accepted upstream.
