### ISSUE TITLE
Build for Terraform 0.8.x

### ISSUE THREAD

**Issue by tdooner** [donaldguy/terraform-provider-twilio#2]
Hello! Thanks for writing this plugin, I recently needed this for a project and it seems to have worked great... when I built it myself for Terraform 0.8.x.

Would it be possible for you to publish a release of the provider that was built against Terraform 0.8.6? If you'd like me to build it myself and send you the binaries, I'd be happy to do that!

**Comment by donaldguy** [comment]
We actually are putting on pause on using terraform at tulip in general; I'm gonna give you collab privileges on the repo, if you want to throw up a new release for 0.8/0.9 feel free

**Comment by donaldguy** [comment]
(but if you are gonna push upstream, please include the linux build)

**Comment by tdooner** [comment]
Great thanks for the reply and the collaborator privileges! I'll think about how to proceed -- my Go skills are still pretty basic, but at least publishing some releases for 0.8/0.9 should be possible.

**Comment by donaldguy** [comment]
If you want me to code review something, still feel free to open a PR
